[project]
name = "salesforce_api"
version = "0.0.1"
authors = []
requires-python = ">=3.10,<3.13"
dependencies = [
    "databricks-sdk>=0.20.0",
    "requests>=2.31.0",
]

[[tool.uv.index]]
name = "databricks-proxy"
url = "https://pypi-proxy.cloud.databricks.com/simple/"
default = true

[tool.hatch.build.targets.wheel]
packages = [
    "src/python_operator_task",
    "src/salesforce_api",
]

[dependency-groups]
dev = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
